#!/bin/bash

set -e

[ "$1" = remove ] || exit 0

RESTART=
STOP=

remove_symlink() {
  src=$1 dest=$2
  # restore original binaries if symlinks present...
  if [ -h $dest -a "$(LANG=en_US.utf8 ls -dn $dest 2>/dev/null | awk '{ print $10 }')" = $src ]; then
    rm -f $dest
    # restore original (if available)
    [ -f ${dest}.orig ] && mv ${dest}.orig $dest || STOP=1
    RESTART=1
  fi
  return 0
}

remove_symlink /usr/local/sbin/smbd /usr/sbin/smbd
remove_symlink /usr/local/sbin/nmbd /usr/sbin/nmbd
remove_symlink /usr/local/sbin/winbindd /usr/sbin/winbindd

# stop daemon if changes
if [ -n "$RESTART" ]; then
  if /etc/init.d/samba status &>/dev/null; then
    /etc/init.d/samba stop || :
    # flag postrm to start samba if old binaries were restored
    [ -n "$STOP" ] && rm -f /tmp/samba36-addon.start || touch /tmp/samba36-addon.start
  else
    rm -f /tmp/samba36-addon.start
  fi
fi

exit 0
